### ISSUE TITLE
Current value XKB_DEFAULT_LAYOUT ?

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#255]
The environment variable XKB_DEFAULT_LAYOUT=lx,ly is set in labwc.
How to output the current value in sfwbar?

**Comment by LBCrion** [comment]
This can be done by calling "sh -c set" from a scanner and parsing it's output, but that would display the value sfwbar inherited from labwc at the time of launch. If the layout changes subsequently (i.e. via labwc --reload). sfwbar's environment won't get this update.

@Consolatis, do you know if labwc would update the environment of the main process when the layout changes? If it does, we could in theory monitor the environment of the labwc process via /proc for layout changes.

**Comment by sfs-pra** [comment]
"sh -c set" will show the same XKB_DEFAULT_LAYOUT=lx,ly in all cases.
I want to determine which layout is currently lx or ly. To make indication in sfwbar
I.e. I need an analog of https://aur.archlinux.org/packages/xkbmon for wayland + labwc.

**Comment by Consolatis** [comment]
We just merged https://github.com/labwc/labwc/pull/2274.
That causes modifier events including the group modifier to be broadcasted to all clients so a panel could use the group modifier to figure out the layout based on the keymap.

**Comment by sfs-pra** [comment]
Updated  labwc-git-0.8.1.r9.g2b877d22-2-x86_64.pkg.tar.zst
1. In sfwbar the pager worked. But in tooltype the window is completely black
2. It worked : https://github.com/johanmalm/keyboard-layout
<keyboard layoutScope=“”> [global|window] - works in both cases
sway-lang.widget wbar-sway-lang.widget - still not working

Thanks. Now I can write labwc-lang.widget

**Comment by LBCrion** [comment]
The pager previews won't show anything on labwc right as there is still no protocol to associate the toplevels with workspaces and get toplevel geometry.
sway-lang.widget is sway specific (it relies on sway socket ipc to receive the info).

Let me have a look at the modifier based keyboard layout info. It should be possible to write a module to handle it and expose the current keymap.

**Comment by sfs-pra** [comment]
scanner {
  Exec("keyboard-layout") {
    MyVar = Grab()
  } 
  It doesn't work that way. What's the correct way to use https://github.com/johanmalm/keyboard-layout ?

**Comment by LBCrion** [comment]
Try this:
```
ExecClient("stdbuf -oL keyboard-layout", "labwc-layout") {
  LayoutText = Grab()
}

layout {
  label {
    value = $LayoutText
    trigger = "labwc-layout"
  }
}
```

**Comment by sfs-pra** [comment]
Works! Thanks
Improved:
```
#https://github.com/johanmalm/keyboard-layout
#change lx -> you lang
ExecClient("stdbuf -oL keyboard-layout", "labwc-layout") {
  LayoutText = Grab()
}

layout {
  image {
    style = "value_icon1"
    value = if($LayoutText = "English (US)","icons/flag/flag-us.png","icons/flag/flag-lx.png")
    trigger = "labwc-layout"
    tooltip = "Lclick to change Keyboard Layout"
    action = Exec "labwc-key-layout.sh"
  }

  label {
    style = "value"
    value = if($LayoutText = "English (US)","En","lx")
    trigger = "labwc-layout"
    style = "value"
    interval = 3000
  }
}
```
```
#!/bin/ash
#https://github.com/v1cont/yad
ll="`awk -F= '/^XKB_DEFAULT_LAYOUT=/ {print $2}' ~/.config/labwc/environment`"
lo="`awk -F= '/^XKB_DEFAULT_OPTIONS=/ {print $2}' ~/.config/labwc/environment |sed 's/^grp://'`"
l="$lo
`awk '/grp:/ {print $1}' /usr/share/X11/xkb/rules/xorg.lst |sort |sed 's/^grp://'`"
echo $ll; echo $lo
l="`yad --title="Keyboard Layout" \
    --text="Keyboard Layout" \
    --image="input-keyboard" \
    --window-icon="input-keyboard" \
    --item-separator="\n" \
    --fixed --image-on-top --center \
    --form \
    --field="XKB DEFAULT LAYOUT"  $ll \
    --field="XKB DEFAULT OPTIONS":CBE "$l" \
`"
[ "$l" ] || exit
ll="`echo $l |awk -F\| '{print $1}'`"
lo="`echo $l |awk -F\| '{print $2}'`"
echo $ll ;echo $lo
sed -i 's/XKB_DEFAULT_LAYOUT=.*/XKB_DEFAULT_LAYOUT='$ll'/' ~/.config/labwc/environment
sed -i 's/XKB_DEFAULT_OPTIONS=.*/XKB_DEFAULT_OPTIONS=grp:'$lo'/' ~/.config/labwc/environment
export XKB_DEFAULT_LAYOUT=="$ll"
export XKB_DEFAULT_OPTIONS="$lo"
labwc -r
```

**Comment by LBCrion** [comment]
You can probably use xkbmap module to convert layout names to abbreviations
and use those in flag filenames.

**Comment by sfs-pra** [comment]
```
value = "icons/flag/flag-" + XkbMap($LayoutText,"description","name") + ".png"
value = Upper(XkbMap($LayoutText,"description","name"))
```
Yeah. It's more versatile

The variable didn't work :
```
Lt = XkbMap($LayoutText,"description","name")
value = "icons/flag/flag-" + $Lt + ".png"
```
What did I do wrong?

**Comment by LBCrion** [comment]
The variable should be declared with Set Lt = XkbMap ...
And this statement should be outside all blocks (I.e. outside of Layout {}).

**Comment by sfs-pra** [comment]
So it worked. Thank you
